### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by JaeminKIM-Irene** [JaeminKIM-Irene/Git_GH_Flow_Practice#2]
## Tasks

- [x] Print fizz if i is multiple of 3
- [x] Print buss if i is multiple of 5
- [x] Print fizzbuzz if i is multiple of 15
- [x] Otherwise, print i itself

## References
[Fizzbuzz Wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
